# Generated by Django 2.2 on 2021-07-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.BigIntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
