# Generated by Django 2.2 on 2021-07-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_auto_20210708_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
