# Generated by Django 2.2 on 2021-07-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_auto_20210710_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
