# Generated by Django 2.2 on 2021-07-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(max_length=20, unique=True)),
                ('loading_point', models.CharField(max_length=20)),
                ('unloading_point', models.CharField(max_length=20)),
                ('quanity', models.FloatField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle_app.Vehicle')),
            ],
        ),
    ]
