# Generated by Django 2.2 on 2021-07-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('permit_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('loading_point', models.CharField(max_length=20)),
                ('unloading_point', models.CharField(max_length=20)),
                ('quanity', models.FloatField()),
                ('permit_date', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vechicle_permits', to='vehicle_app.Vehicle')),
            ],
            options={
                'ordering': ['-permit_date'],
            },
        ),
    ]
