# Generated by Django 2.2 on 2021-07-11 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('permit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='permit_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
