# Generated by Django 2.2 on 2021-07-10 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gps_imei', models.BigIntegerField(unique=True)),
                ('license_start', models.DateField()),
                ('license_end', models.DateField()),
                ('vehicle_category', models.CharField(choices=[('DMG', 'DMG'), ('Stockyard', 'Stock-Yard')], default='DMG', max_length=9)),
                ('vehicle_type', models.CharField(choices=[('Tipper', 'Tipper'), ('Tractor', 'Tractor'), ('Lorry', 'Lorry')], default='Tipper', max_length=15)),
                ('total_permits', models.PositiveIntegerField(default=0)),
                ('installation_type', models.CharField(choices=[('New Installation', 'New Installation'), ('Migration', 'Migration'), ('Renewal with existing hardware', 'Renewal with existing hardware')], default='New Installation', max_length=30)),
                ('registration_date', models.DateField()),
                ('vehicle_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
