# Generated by Django 2.2 on 2021-07-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gps_imei', models.BigIntegerField(unique=True)),
                ('license_start', models.DateField()),
                ('license_end', models.DateField(blank=True)),
                ('vehicle_category', models.CharField(choices=[('DMG', 'DMG'), ('Stockyard', 'Stockyard')], default='DMG', max_length=9)),
                ('vehicle_type', models.CharField(choices=[('Tipper', 'Tipper'), ('Tractor', 'Tractor'), ('Lorry', 'Lorry')], default='Tipper', max_length=15)),
                ('total_permits', models.PositiveIntegerField(default=0)),
                ('installation_type', models.CharField(choices=[('New Installation', 'New Installation'), ('Migration', 'Migration'), ('Renewal with existing hardware', 'Renewal with existing hardware')], default='New Installation', max_length=30)),
                ('registration_date', models.DateField()),
                ('vehicle_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.Client')),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
    ]
