# Generated by Django 2.2 on 2021-07-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_end',
            field=models.DateField(blank=True),
        ),
    ]
