# Generated by Django 2.2 on 2021-07-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-vehicle_number', '-registration_date']},
        ),
    ]
